apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-cl-depl1
  labels:
    app: fl-cl1
spec:
  selector:
    matchLabels:
      app: fl-cl1
  template:
    metadata:
      labels:
        app: fl-cl1
    spec:
      containers:
      - name: fl-cl1
        image: cilicivan96/aiotwin-fl-client:1.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/config/example_client/client_config.yaml
          name: configyaml1
      volumes:
      - name: configyaml1
        hostPath: 
          path: /home/ivan/aiotwin/software/fl-orchestrator/deployment_scripts/hierarchical/configs/client_config_1.yaml
          type: File
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-cl-depl2
  labels:
    app: fl-cl2
spec:
  selector:
    matchLabels:
      app: fl-cl2
  template:
    metadata:
      labels:
        app: fl-cl2
    spec:
      containers:
      - name: fl-cl2
        image: cilicivan96/aiotwin-fl-client:1.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/config/example_client/client_config.yaml
          name: configyaml2
      volumes:
      - name: configyaml2
        hostPath: 
          path: /home/ivan/aiotwin/software/fl-orchestrator/deployment_scripts/hierarchical/configs/client_config_2.yaml
          type: File
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-cl-depl3
  labels:
    app: fl-cl3
spec:
  selector:
    matchLabels:
      app: fl-cl3
  template:
    metadata:
      labels:
        app: fl-cl3
    spec:
      containers:
      - name: fl-cl3
        image: cilicivan96/aiotwin-fl-client:1.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/config/example_client/client_config.yaml
          name: configyaml3
      volumes:
      - name: configyaml3
        hostPath: 
          path: /home/ivan/aiotwin/software/fl-orchestrator/deployment_scripts/hierarchical/configs/client_config_3.yaml
          type: File
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-cl-depl4
  labels:
    app: fl-cl4
spec:
  selector:
    matchLabels:
      app: fl-cl4
  template:
    metadata:
      labels:
        app: fl-cl4
    spec:
      containers:
      - name: fl-cl4
        image: cilicivan96/aiotwin-fl-client:1.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/config/example_client/client_config.yaml
          name: configyaml4
      volumes:
      - name: configyaml4
        hostPath: 
          path: /home/ivan/aiotwin/software/fl-orchestrator/deployment_scripts/hierarchical/configs/client_config_4.yaml
          type: File