apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-ls-depl1
  labels:
    app: fl-ls1
spec:
  selector:
    matchLabels:
      app: fl-ls1
  template:
    metadata:
      labels:
        app: fl-ls1
    spec:
      containers:
      - name: fl-ls1
        image: cilicivan96/aiotwin-fl-local-server:1.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/config/example_local_server/aggregator_config.yaml
          name: configyamlls1
      volumes:
      - name: configyamlls1
        hostPath: 
          path: /home/ivan/aiotwin/software/fl-orchestrator/deployment_scripts/hierarchical/configs/aggregator_config_1.yaml
          type: File
---
apiVersion: v1
kind: Service
metadata:
  name: fl-ls-service1
spec:
  type: NodePort
  selector:
    app: fl-ls1
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30008
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-ls-depl2
  labels:
    app: fl-ls2
spec:
  selector:
    matchLabels:
      app: fl-ls2
  template:
    metadata:
      labels:
        app: fl-ls2
    spec:
      containers:
      - name: fl-ls2
        image: cilicivan96/aiotwin-fl-local-server:1.0
        ports:
        - containerPort: 5000
        volumeMounts:
        - mountPath: /app/config/example_local_server/aggregator_config.yaml
          name: configyamlls2
      volumes:
      - name: configyamlls2
        hostPath: 
          path: /home/ivan/aiotwin/software/fl-orchestrator/deployment_scripts/hierarchical/configs/aggregator_config_2.yaml
          type: File
---
apiVersion: v1
kind: Service
metadata:
  name: fl-ls-service2
spec:
  type: NodePort
  selector:
    app: fl-ls2
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30009
