apiVersion: apps/v1
kind: Deployment
metadata:
  name: fl-gs-depl
  labels:
    app: fl-gs
spec:
  selector:
    matchLabels:
      app: fl-gs
  template:
    metadata:
      labels:
        app: fl-gs
    spec:
      containers:
      - name: fl-gs
        image: cilicivan96/aiotwin-fl-global-server:1.0
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: fl-gs-service
spec:
  type: NodePort
  selector:
    app: fl-gs
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30007
